### ISSUE TITLE
Option to specify a custom CSS style for an individual trial

### ISSUE THREAD

**Issue by gavinmporter** [jodeleeuw/jsPsych#170]
For a recent experiment I wanted to use the single-stim plugin in more than one way - a) with the default CSS, and b) with a separate style to centre the stimuli on the screen. This allowed me to keep the original jsPsych CSS file unmodified whilst introducing a custom style for part of the experiment.

I added support to the single-stim plugin by adding a new optional variable, css_id. This approach could be extended to other plugins. Is that desirable? and if so which ones?

My changes so far can be seen here: https://github.com/jodeleeuw/jsPsych/compare/master...gavinmporter:custom_stimuli_css?expand=1

Gavin

**Comment by jodeleeuw** [comment]
I think this is an interesting idea. I considered [something similar earlier on in development](https://github.com/jodeleeuw/jsPsych/issues/16) but ultimately gave up on it because you can always use the is_html parameter and embed custom CSS that way. However, something like this is easier, and preferable for when people are using only images.

I think I would hold off on making this kind of change until #163 gets sorted out and there is more of a standard on how CSS will be woven into the fabric of jspsych. I think a retooling of CSS support in general will make the right way to handle this scenario more obvious.

**Comment by jodeleeuw** [comment]
This will be handled by #357
